name: 'Wordfence Malware Scan'

inputs:
  license:
    required: true
  version:
    default: main
  path:
    default: .
    required: false
  workers:
    default: 1
runs:
  using: 'composite'
  steps:
    - name: Install wordfence
      shell: bash
      run: |
        git clone -b ${{ inputs.version }} https://github.com/wordfence/wordfence-cli.git /tmp/wordfence-cli
        docker build -t wordfence-cli:${{ inputs.version }} /tmp/wordfence-cli/

    - name: Run wordfence
      shell: bash
      run: |
        docker run -v ${{ inputs.path }}:/var/www wordfence-cli:${{ inputs.version }} malware-scan \
          --no-cache \
          --no-banner \
          --no-color \
          --license=${{ inputs.license }} \
          --workers=${{ inputs.workers }} \
          --include-all-files \
          /var/www/
