name: Malware scan
on:
  workflow_call:
    secrets:
      license:
        required: true
jobs:
  build:
    name: Malware scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run malware scan
        uses: generoi/github-action-wordfence-malware-scan@master
        with:
          license: ${{ secrets.license }}
